version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - '80:80'
    - '443:443'
    expose:
    - "80"
    - "433"
    volumes:
    - ./docker/logs/nginx:/var/log/nginx
    links:
    - wordpress
    - starward
    restart: always
